export const projectList1 = [
    {
        title: '국립현대미술관 유지관리',
        desc: ['2024.01', '웹접근성 인증마크 갱신 작업'],
        stack: ['웹접근성'],
        homepage: 'https://artbank.go.kr/',
    },
    {
        title: '행정안전부 범정부 데이터 분석시스템 확대 구축',
        desc: ['2023.10 ~ 2024.04', '프론트 UI 리뉴얼 구축'],
        stack: ['Html', 'Javascript', 'jQuery', 'CSS'],
        homepage: 'https://insight.go.kr/',
    },
    {
        title: '문화공공데이터 연계 통합관리 체계 운영 및 유지관리',
        desc: ['2023.04 ~ 현재', '메인 포함 일부 페이지 UI 개선', '운영 및 유지 보수 관리'],
        stack: ['Html', 'Javascript', 'jQuery', 'CSS'],
        homepage: 'https://www.culture.go.kr/data/main/main.do',
    },
    {
        title: '아르떼 웹사이트 UI 화면단 리뉴얼 구축',
        desc: ['2023.07 ~ 2023.09', 'html 산출물 react 컴포넌트(jsx)로 변환하여 UI 적용', '기타 오류 수정'],
        stack: ['React', 'Next.js', 'jQuery', 'CSS'],
        homepage: 'https://www.arte.co.kr/',
    },
    {
        title: '숭실사이버대학교 차세대 통합정보시스템 구축',
        desc: ['2023.01 ~ 현재', '반응형 / 다국어 리뉴얼 구축', '웹접근성에 준수하여 마크업 작성 (오픈 후 인증마크 획득 예정)'],
        stack: ['Html', 'jQuery', 'CSS', '웹접근성'],
    },
    {
        title: '소방안전 빅테이터 플랫폼 웹사이트 구축',
        desc: ['2022.12 ~ 2023.03', '반응형 리뉴얼 구축'],
        stack: ['Html', 'jQuery', 'CSS'],
        homepage: 'https://www.bigdata-119.kr/',
    },
    {
        title: '빙그레 기업사이트 리뉴얼 구축',
        desc: ['2022.05 ~ 2022.07', '지속가능경영, 투자정보 반응형 구축', '주가정보 API 연동'],
        stack: ['Thymeleaf', 'Javascript', 'jQuery', 'SCSS'],
        homepage: 'https://www.bing.co.kr/',
    },
    {
        title: '웹사이트 구축 기반용 CMS 플랫폼 구축',
        desc: ['2022.05 ~ 2022.07', 'CMS 프론트 페이지 반응형 구축', '재사용될 수 있도록 공통 영역 모듈화'],
        stack: ['Thymeleaf', 'Javascript', 'jQuery', 'SCSS'],
    },
    {
        title: 'NHN Shop by pro 스킨 제작',
        desc: ['2022.05 ~ 2022.07', '고도에서 신규로 출시한 샵바이 프로 영업 및 판매를 목표로 스킨 제작', '웹/모바일 적응형 구축'],
        stack: ['Handlebars', 'Javascript', 'jQuery', 'SCSS'],
    },
    {
        title: '고운세상코스메틱 기업사이트 리뉴얼 구축',
        desc: ['2021.12 ~ 2022.02', '메인페이지 반응형 구축', 'GSAP, ScrollMagic 라이브러리 기반으로 슬라이드 구현'],
        stack: ['Thymeleaf', 'jQuery', 'CSS', 'GSAP'],
        homepage: 'https://www.gowoonsesang.com/',
    },
    {
        title: '뮤자인 웹사이트 리뉴얼 구축',
        desc: ['2021.12 ~ 2022.02', 'CANVAS를 사용하여 라인 인터렉션 구현 (메인 인트로, 마우스 포커스에 따라 튕기는 효과)', 'GSAP, Draggable 라이브러리 기반으로 슬라이드 구현'],
        stack: ['Thymeleaf', 'jQuery', 'CANVAS', 'GSAP', 'CSS'],
        homepage: 'https://musign.net/',
    },
    {
        title: '뉴트리몰 이커머스 유지보수',
        desc: ['2021.01 ~ 2022.07', '부분 리뉴얼', '스타일가이드 통일 작업', '오류 및 최적화 작업', '신규 기능에 따른 작업', '이벤트 퍼블리싱'],
        stack: ['메이크샵', 'Javascript', 'jQuery', 'CSS'],
        homepage: 'https://www.newtreemall.co.kr/',
    },
    {
        title: 'SPC 기업사이트 리뉴얼 구축',
        desc: ['2021.03 ~ 2021.12', '반응형, 다국어 구축', '인스타그램, 유튜브 API 연동', 'SVG를 사용하여 path가 그려지는 인터렉션 구현'],
        stack: ['Wordpress', 'Javascript', 'jQuery', 'CSS'],
        homepage: 'https://www.spc.co.kr/',
    },
    {
        title: '닥터포헤어 이커머스 리뉴얼 구축',
        desc: ['2021.001 ~ 2021.06', '웹 / 모바일 적응형 구축', '브랜드스토리 인터렉션 구현'],
        stack: ['Godomall5', 'Javascript', 'jQuery', 'CSS'],
        homepage: 'https://www.drforhair.co.kr/',
    },
    {
        title: 'V&A뷰티 이커머스 구축',
        desc: ['2021.03 ~ 2021.12', '웹 / 모바일 적응형 구축', '브랜드스토리 스크롤 인터렉션 구현'],
        stack: ['Godomall5', 'Javascript', 'jQuery', 'CSS'],
        homepage: 'https://www.va-beauty.com/',
    },
    {
        title: 'AK문화센터 웹사이트 및 관리시스템 구축',
        desc: ['2020.09 ~ 2021.09', ' 프론트 웹페이지 반응형 구축', '관리시스템 페이지 웹 구축 (150p 이상)', '스크롤 인터렉션 구현'],
        stack: ['Godomall5', 'Javascript', 'jQuery', 'CSS'],
        homepage: 'https://culture.akplaza.com/main',
    },
    {
        title: 'TLI 웹사이트 리뉴얼 구축',
        desc: ['2021 (3개월)', '반응형, 다국어 구축', '인트로 인터렉션 구현', '제품소개 페이지 인터렉션 구현'],
        stack: ['Html', 'Javascript', 'jQuery', 'CSS'],
        homepage: 'https://www.tli.co.kr/',
    },
    {
        title: 'TLI 웹사이트 리뉴얼 구축',
        desc: ['2021 (3개월)', '반응형, 다국어 구축', '인트로 인터렉션 구현', '제품소개 페이지 인터렉션 구현'],
        stack: ['Html', 'Javascript', 'jQuery', 'CSS'],
        homepage: 'https://www.tli.co.kr/',
    },
    {
        title: '홍루이젠 기업, 가맹점주 사이트 리뉴얼 구축',
        desc: ['2021 (3개월)', '웹 / 모바일 적응형 구축'],
        stack: ['Godomall5', 'Javascript', 'jQuery', 'CSS'],
        homepage: 'https://www.hongruizhen.com/',
    },
    {
        title: '티르티르 이커머스 리뉴얼 구축',
        desc: ['2020 (6개월)', '웹 / 모바일 적응형 구축'],
        stack: ['Godomall5', 'Javascript', 'jQuery', 'CSS'],
        homepage: 'https://www.tirtir.co.kr/',
    },
    {
        title: '디어스 기업사이트 리뉴얼 구축',
        desc: ['2019', 'SVG 인터렉션', '스크롤 인터렉션 구현', 'CI 로고 애니메이션 구현'],
        stack: ['Wordpress', 'Javascript', 'jQuery', 'CSS'],
        homepage: 'http://deers.co.kr/',
    },
    {
        title: '이너시그널 이커머스 구축',
        desc: ['2019 (6개월)', '웹 / 모바일 적응형 구축'],
        stack: ['Godomall5', 'Javascript', 'jQuery', 'CSS'],
        homepage: 'https://www.innersignal.co.kr/',
    },
    {
        title: '아티스트컴퍼니 웹사이트 구축',
        desc: ['2017 (3개월)', '반응형 구축'],
        stack: ['Wordpress', 'Javascript', 'jQuery', 'CSS'],
        homepage: 'https://www.artistcompany.co.kr//',
    },
]

export const projectList2 = [
    {
        title: '영화, TV 홈페이지 제작',
        desc: ['api를 모듈화하고 react-query로 데이터 패칭', '반복되는 카드 영역은 코드 재사용을 위해 컴포넌트 분리', 'mui의 Rating 컴포넌트를 사용하여 간편하게 별점 구현'],
        stack: ['React', 'Typescript', 'Axios', 'React-Query', 'emotion', 'mui', 'react-icons'],
        homepage: 'https://watcha-pedia.netlify.app/',
        git: 'https://github.com/wldbszpflrxj/typescript-watcha-pedia',
    },
    // {
    //     title: 'React Router 기능 구현',
    //     desc: ['context API를 사용하여 하위 컴포넌트에서 주소 변경이 일어날 경우 렌더링 될 수 있도록 전역상태관리 ', 'History API를 사용하여 React-router-dom 기능을 구현'],
    //     stack: ['React', 'Javascript', 'context Api'],
    //     homepage: 'https://spa-router.netlify.app/',
    //     git: 'https://github.com/wldbszpflrxj/react-router',
    // },
    {
        title: '투자 관리 서비스의 관리자 기능 구현',
        desc: ['server json의 search api를 사용하여 검색 기능을 구현', 'query string으로 데이터를 전달하여 사용자의 편의성 고려', 'ID 기반으로 데이터 매칭이 필요한 값은 재사용성을 위해 hook 생성'],
        stack: ['React', 'Json-server Api', 'Axios', 'Redux', 'Chakra UI', 'emotion'],
        git: 'https://github.com/wldbszpflrxj/6th_investment-admin',
    },
    {
        title: '깃헙 레파지토리 이슈 관리',
        desc: ['react-markdown을 사용하여 마크다운 렌더링', 'mui 컴포넌트를 사용하여 반응형 대응'],
        stack: ['React', 'github Api', 'Axios', 'context Api', 'mui'],
        homepage: 'https://github-issue-viewer-team2.netlify.app/',
        git: 'https://github.com/wldbszpflrxj/4th_github-issue-viewer/',
    },
    // {
    //     title: '댓글 목록 CRUD',
    //     desc: ['useState를 사용하여 페이지네이션 구현', 'page와 limit 값을 활용하여 api 호출'],
    //     stack: ['React', 'Json-server Api ', 'Axios', 'Redux thunk', 'emotion'],
    //     git: 'https://github.com/wldbszpflrxj/5th_comments-list',
    // },
    // {
    //     title: '프루떼 스토어 리뉴얼',
    //     desc: ['Redux-persist 기능을 Api 대체 기능으로 사용하여 로컬스토리지에 데이터를 저장', 'Redux를 통해 상품 관리, 주문 상태 관리 '],
    //     stack: ['React', 'Axios', 'Redux', 'mui', 'emotion'],
    //     homepage: 'https://fruitte-renewal.netlify.app/',
    //     git: 'https://github.com/wldbszpflrxj/2nd_fruitte',
    // },
]
